.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.TH taxa 1 "FEB 2025" Taxa "User Manuals"
.SH "NAME"
taxa \- extract taxon lists from a Darwin Core archive
.
.SH "SYNOPSIS"
.B taxa
.RB [ \-n0 ]
.I src-dir
.I taxon
\&...
.br
.B taxa
.RB [ \-n0 ]
.B --taxa
.I file
.B --names
.I file
.B --dist
.I file
.I taxon
\&...
.br
.B taxa --help
.br
.B taxa --version
.
.
.SH "DESCRIPTION"
.
.B taxa
reads
.B "Darwin Core Archive"
.RB ( DwC-A )
files, specifically those published by
.IR Artdatabanken ,
and prints flat taxon lists, e.g.
.IP
.nf
.ft CW
# Solanaceae
belladonna		(Atropa bella-donna)
indisk spikklubba	(Datura metel)
spikklubba		(Datura stramonium)
\&...
.fi
.
.PP
This format is the same used by
.B gavia
and
.BR groblad ,
and defined in
.BR groblad_species (5).
.
.PP
What's printed is every defined taxon under
.IR taxon ,
such as all genera, sections, species and subspecies in a plant family.
Also, for each taxon, all its documented synonyms.
The taxa are sorted by scientific name.
.
.PP
DwC-A is defined, I suppose, as an MS-DOS ZIP file, but since that's an inconvenient
format in many ways,
.B taxa
assumes it has been unpacked into several CSV files.
It uses three of these:
.BR Taxon.csv ,
.B VernacularName.csv
and
.BR SpeciesDistribution.csv .
.
.
.SS "The data model"
.
DwC data (at least as published by Artdatabanken) includes:
.IP \- 3x
One accepted name (and auctor) for each taxon.
.PD 0
.IP \-
Frequently, synonyms of varying quality. Some might be well-known, while others are archaic.
.IP \-
Taxa at different ranks:
.BR family ,
.BR genus ,
.BR species ,
.BR subspecies ,
.BR variety .
Also
.BR aggregates ,
.B sections
(like those in
.IR Taraxacum ),
.B forms
and
.BR cultivars .
As usual, the taxa form a hierarchy.
.IP \-
Optionally, a preferred swedish name for the taxon.
.IP \-
Also optionally, other swedish names for the taxon.
The swedish names are never tied to a synonym but to the taxon as a whole,
as understood today.
.IP \-
For many taxa, their
.B occurrence
(which may be
.BR absent )
and
.BR "threat status" .
.PD
.PP
More data is present, but this is roughly what's relevant to
.BR taxa .
.
.
.SS "Taxon lists"
.
For each taxon specified, there's a section with a heading. The
sections appear in the order specified on the command line; this lets
you get the list in a familiar order (e.g. ferns first and grasses
last, if that's what you're used to).
.PP
In each section, the directly underlying taxa are printed in alphabetic order,
i.e. sorted by accepted scientific name. Taxa marked as
.B absent
in Sweden are skipped; so are
.BR cultivars .
.PP
If there's a preferred swedish name, it's printed on the first line.
All other important synonyms, scientific and otherwise,
appear on the following lines:
.IP
.nf
.ft CW
paddfot                 (Asperugo procumbens)
= riva
.fi
.PP
Then underlying taxa follow, according to the same principles. So subspecies
appear directly after the species;
.I Taraxacum
is arranged into its sections, and so on.
.
.
.SS "Data quality"
.
If you investigate the data, you find unnecessary or uninteresting names.
I have found these patterns and deviations:
.IP \- 3x
Hybrids being specified by the letter x rather than the multiplication sign ×.
I choose the correct character.
.PD 0
.IP \-
.I ssp.
versus
.I subsp.
I choose the former because that's what I'm used to and for aesthetical reasons.
Artportalen chooses the latter.
.IP \-
Hybrid ordering:
.I "foo × bar"
versus
.IR "bar × foo" .
It's not clear to me whether these mean the same thing everywhere, and I'm too
lazy to check.
.IP \-
Misspellings, and different ways to avoid using accented characters.
.IP \-
Archaic scientific names, which haven't been used in the literature in my lifetime.
Hard to tell how common this is; it may vary in different parts of the input.
.IP \-
Capitalization. Some major sources of alternate names apparently capitalize
all names. It's not possible to compensate for this without damaging names where
capitalization is proper.
.IP \-
Pointless swedish names, like names for races of birds.
.PD
.PP
Except as noted, there is nothing I can do about this.
.
.
.SH "OPTIONS"
.
.BP \-n
Don't list synonyms, just the accepted scientific name and (if available) the preferred
swedish name.
.
.BP \-0
Don't recurse; just print all immediate child taxa.
.
.BP --taxa\ \fIfile
.BR Taxon.csv .
This, and
.B --names
and
.BR --dist ,
give detailed control, but usually you'll want to specify
.I src-dir
containing these three files.
.
.BP --names\ \fIfile
.BR VernacularName.csv .
.
.BP --dist\ \fIfile
.BR SpeciesDistribution.csv .
.
.BP --help
Print a brief help text and exit.
.
.BP --version
Print version information and exit.
.
.
.SH "AUTHOR"
.
J\(:orgen Grahn
.IR \[fo]grahn@snipabacken.se\[fc] .
.
.
.SH "LICENSE"
The GNU General Public License (GPL) version 2 or (at your option) version 3.
.
.
.SH "SEE ALSO"
.
.BR groblad_species (5).
.br
.RB \[fo] https://metadata.artfakta.se/taxonomiskdata \[fc].
